# Generated by Django 4.1.6 on 2023-02-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propertyManager", "0005_alter_propertydetail_adhar_pic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="property_to_excel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(null=True, upload_to="propertyfile")),
            ],
        ),
    ]
