# Generated by Django 4.1.6 on 2023-02-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propertyManager", "0009_alter_propertydetail_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertydetail",
            name="email",
            field=models.EmailField(
                default=None, max_length=254, null=True, unique=True
            ),
        ),
    ]
