# Generated by Django 4.1.6 on 2023-02-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propertyManager", "0011_alter_propertydetail_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertydetail",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
