# Generated by Django 4.1.6 on 2023-02-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propertyManager", "0013_remove_propertydetail_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertydetail",
            name="is_tenant",
            field=models.BooleanField(default=True),
        ),
    ]
