# Generated by Django 4.1.6 on 2023-02-28 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("propertyManager", "0014_propertydetail_is_tenant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertydetail",
            old_name="is_tenant",
            new_name="is_tenant_active",
        ),
    ]
